### ISSUE TITLE
fixed time window null point exceptions

### ISSUE THREAD

**Issue by maguec** [aphyr/riemann#498]
====================================================================================================================
Event
====================================================================================================================
 
```clj
2015-01-21_00:15:02.35049 #riemann.codec.Event{:host "client", :service "web_hit_404", :state nil, :description nil, :metric 1.0, :tags nil, :time 1421799301, :ttl nil}
``` 

====================================================================================================================
Config
====================================================================================================================

```clj
; -*- mode: clojure; -*-
; vim: filetype=clojure
 
(logging/init {:file "riemann.log"})
 
; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))
 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; set of severity functions - Use for alerting escalation!
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defn severity
  [severity message & children]
  (fn [e] ((apply with {:state severity :description message} children) e)))
 
(def informational (partial severity "informational"))
(def normal (partial severity "normal"))
(def warning (partial severity "warning"))
(def minor (partial severity "minor"))
(def major (partial severity "major"))
(def critical (partial severity "critical"))
 
; Expire old events from the index every 60 seconds.
(periodically-expire 60)
 
(let [index (index)]
  ; All streams go here
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;  Time window example; TODO: figure out NPE
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (streams
      (where (and (service #"web_hit_404$") (not (expired? event)))
        (fixed-time-window 10
          (combine riemann.folds/sum
            (where (> metric 5.0)
              (fn [event] (warn "WEB_404s" event)))
 
  ))))
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;  Handle expired events
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (streams
    ;prn
    (default :ttl 60
      ; Index all events immediately.
      index
 
      ; Log expired events.
      (expired
        ; we'll always get cpu-0.cpu-idle from any machine running collectd, so it will act as our heartbeat
        (match :service "cpu-0.cpu-idle"
        (fn [event] (info "expired" event)))
       
        )))
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
)
```
 
====================================================================================================================
Error
====================================================================================================================
 
```
2015-01-21_00:11:46.81262 WARN [2015-01-21 00:11:46,812] defaultEventExecutorGroup-2-1 - riemann.config - WEB_404s #riemann.codec.Event{:host client, :service web_hit_404, :state nil, :description nil, :metric 100.0, :tags nil, :time 1421799043, :ttl nil}
2015-01-21_00:11:46.82088 WARN [2015-01-21 00:11:46,819] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.config$eval41$stream__45@2ed233bc threw
2015-01-21_00:11:46.82104 java.lang.NullPointerException
2015-01-21_00:11:46.82125       at clojure.lang.Numbers.gt(Numbers.java:3795)
2015-01-21_00:11:46.82152       at riemann.config$eval41$stream__45.invoke(riemann.config:39)
2015-01-21_00:11:46.82178       at riemann.streams$smap_STAR_$stream__2410$fn__2421.invoke(streams.clj:151)
2015-01-21_00:11:46.82214       at riemann.streams$smap_STAR_$stream__2410.invoke(streams.clj:151)
2015-01-21_00:11:46.82231       at riemann.streams$fixed_time_window$stream__2686$fn__2719.invoke(streams.clj:381)
2015-01-21_00:11:46.82256       at riemann.streams$fixed_time_window$stream__2686.invoke(streams.clj:381)
2015-01-21_00:11:46.82282       at riemann.config$eval41$stream__88$fn__93.invoke(riemann.config:36)
2015-01-21_00:11:46.82306       at riemann.config$eval41$stream__88.invoke(riemann.config:36)
2015-01-21_00:11:46.82331       at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
2015-01-21_00:11:46.82357       at riemann.core$stream_BANG_.invoke(core.clj:18)
2015-01-21_00:11:46.82375       at riemann.transport$handle.invoke(transport.clj:162)
2015-01-21_00:11:46.82393       at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
2015-01-21_00:11:46.82412       at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
2015-01-21_00:11:46.82431       at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
2015-01-21_00:11:46.82456       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
2015-01-21_00:11:46.82479       at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
2015-01-21_00:11:46.82516       at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
2015-01-21_00:11:46.82534       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
2015-01-21_00:11:46.82552       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-01-21_00:11:46.82570       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-01-21_00:11:46.82602       at java.lang.Thread.run(Thread.java:745)
2015-01-21_00:11:46.83085 WARN [2015-01-21 00:11:46,826] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.config$eval41$stream__45@2ed233bc threw
2015-01-21_00:11:46.83154 java.lang.NullPointerException
2015-01-21_00:11:46.83188       at clojure.lang.Numbers.gt(Numbers.java:3795)
2015-01-21_00:11:46.83207       at riemann.config$eval41$stream__45.invoke(riemann.config:39)
2015-01-21_00:11:46.83226       at riemann.streams$smap_STAR_$stream__2410$fn__2421.invoke(streams.clj:151)
2015-01-21_00:11:46.83254       at riemann.streams$smap_STAR_$stream__2410.invoke(streams.clj:151)
2015-01-21_00:11:46.83280       at riemann.streams$fixed_time_window$stream__2686$fn__2719.invoke(streams.clj:381)
2015-01-21_00:11:46.83301       at riemann.streams$fixed_time_window$stream__2686.invoke(streams.clj:381)
2015-01-21_00:11:46.83321       at riemann.config$eval41$stream__88$fn__93.invoke(riemann.config:36)
2015-01-21_00:11:46.83342       at riemann.config$eval41$stream__88.invoke(riemann.config:36)
2015-01-21_00:11:46.83360       at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
2015-01-21_00:11:46.83377       at riemann.core$stream_BANG_.invoke(core.clj:18)
2015-01-21_00:11:46.83397       at riemann.transport$handle.invoke(transport.clj:162)
2015-01-21_00:11:46.83414       at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
2015-01-21_00:11:46.83437       at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
2015-01-21_00:11:46.83463       at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
2015-01-21_00:11:46.83485       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
2015-01-21_00:11:46.83506       at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
2015-01-21_00:11:46.83520       at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
2015-01-21_00:11:46.83537       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
2015-01-21_00:11:46.83553       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-01-21_00:11:46.83569       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-01-21_00:11:46.83586       at java.lang.Thread.run(Thread.java:745)
2015-01-21_00:11:46.83814 WARN [2015-01-21 00:11:46,837] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.config$eval41$stream__45@2ed233bc threw
2015-01-21_00:11:46.83855 java.lang.NullPointerException
2015-01-21_00:11:46.83876       at clojure.lang.Numbers.gt(Numbers.java:3795)
2015-01-21_00:11:46.83894       at riemann.config$eval41$stream__45.invoke(riemann.config:39)
2015-01-21_00:11:46.83912       at riemann.streams$smap_STAR_$stream__2410$fn__2421.invoke(streams.clj:151)
2015-01-21_00:11:46.83929       at riemann.streams$smap_STAR_$stream__2410.invoke(streams.clj:151)
2015-01-21_00:11:46.83946       at riemann.streams$fixed_time_window$stream__2686$fn__2719.invoke(streams.clj:381)
2015-01-21_00:11:46.83963       at riemann.streams$fixed_time_window$stream__2686.invoke(streams.clj:381)
2015-01-21_00:11:46.83979       at riemann.config$eval41$stream__88$fn__93.invoke(riemann.config:36)
2015-01-21_00:11:46.83996       at riemann.config$eval41$stream__88.invoke(riemann.config:36)
2015-01-21_00:11:46.84012       at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
2015-01-21_00:11:46.84029       at riemann.core$stream_BANG_.invoke(core.clj:18)
2015-01-21_00:11:46.84032       at riemann.transport$handle.invoke(transport.clj:162)
2015-01-21_00:11:46.84034       at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
2015-01-21_00:11:46.84035       at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
2015-01-21_00:11:46.84037       at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
2015-01-21_00:11:46.84039       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
2015-01-21_00:11:46.84040       at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
2015-01-21_00:11:46.84042       at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
2015-01-21_00:11:46.84045       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
2015-01-21_00:11:46.84048       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-01-21_00:11:46.84049       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-01-21_00:11:46.84051       at java.lang.Thread.run(Thread.java:745)
2015-01-21_00:11:46.84585 WARN [2015-01-21 00:11:46,845] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.config$eval41$stream__45@2ed233bc threw
2015-01-21_00:11:46.84622 java.lang.NullPointerException
2015-01-21_00:11:46.84659       at clojure.lang.Numbers.gt(Numbers.java:3795)
2015-01-21_00:11:46.84731       at riemann.config$eval41$stream__45.invoke(riemann.config:39)
2015-01-21_00:11:46.84779       at riemann.streams$smap_STAR_$stream__2410$fn__2421.invoke(streams.clj:151)
2015-01-21_00:11:46.84807       at riemann.streams$smap_STAR_$stream__2410.invoke(streams.clj:151)
2015-01-21_00:11:46.84837       at riemann.streams$fixed_time_window$stream__2686$fn__2719.invoke(streams.clj:381)
2015-01-21_00:11:46.84859       at riemann.streams$fixed_time_window$stream__2686.invoke(streams.clj:381)
2015-01-21_00:11:46.84895       at riemann.config$eval41$stream__88$fn__93.invoke(riemann.config:36)
2015-01-21_00:11:46.84916       at riemann.config$eval41$stream__88.invoke(riemann.config:36)
2015-01-21_00:11:46.84941       at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
2015-01-21_00:11:46.84960       at riemann.core$stream_BANG_.invoke(core.clj:18)
2015-01-21_00:11:46.84979       at riemann.transport$handle.invoke(transport.clj:162)
2015-01-21_00:11:46.84999       at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
2015-01-21_00:11:46.85035       at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
2015-01-21_00:11:46.85038       at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
2015-01-21_00:11:46.85041       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
2015-01-21_00:11:46.85043       at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
2015-01-21_00:11:46.85044       at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
2015-01-21_00:11:46.85046       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
2015-01-21_00:11:46.85048       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-01-21_00:11:46.85049       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-01-21_00:11:46.85051       at java.lang.Thread.run(Thread.java:745)
2015-01-21_00:11:46.85708 WARN [2015-01-21 00:11:46,853] defaultEventExecutorGroup-2-1 - riemann.streams - riemann.config$eval41$stream__45@2ed233bc threw
2015-01-21_00:11:46.85739 java.lang.NullPointerException
2015-01-21_00:11:46.85768       at clojure.lang.Numbers.gt(Numbers.java:3795)
2015-01-21_00:11:46.85790       at riemann.config$eval41$stream__45.invoke(riemann.config:39)
2015-01-21_00:11:46.85809       at riemann.streams$smap_STAR_$stream__2410$fn__2421.invoke(streams.clj:151)
2015-01-21_00:11:46.85827       at riemann.streams$smap_STAR_$stream__2410.invoke(streams.clj:151)
2015-01-21_00:11:46.85847       at riemann.streams$fixed_time_window$stream__2686$fn__2719.invoke(streams.clj:381)
2015-01-21_00:11:46.85865       at riemann.streams$fixed_time_window$stream__2686.invoke(streams.clj:381)
2015-01-21_00:11:46.85884       at riemann.config$eval41$stream__88$fn__93.invoke(riemann.config:36)
2015-01-21_00:11:46.85901       at riemann.config$eval41$stream__88.invoke(riemann.config:36)
2015-01-21_00:11:46.85919       at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
2015-01-21_00:11:46.85936       at riemann.core$stream_BANG_.invoke(core.clj:18)
2015-01-21_00:11:46.85954       at riemann.transport$handle.invoke(transport.clj:162)
2015-01-21_00:11:46.85973       at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
2015-01-21_00:11:46.85991       at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
2015-01-21_00:11:46.86018       at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
2015-01-21_00:11:46.86046       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
2015-01-21_00:11:46.86168       at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
2015-01-21_00:11:46.86173       at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
2015-01-21_00:11:46.86177       at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
2015-01-21_00:11:46.86180       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
2015-01-21_00:11:46.86184       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
2015-01-21_00:11:46.86187       at java.lang.Thread.run(Thread.java:745)
2015-01-21_00:11:48.72010 WARN [2015-01-21 00:11:48,719] defaultEventExecutorGroup-2-1 - riemann.config - WEB_404s #riemann.codec.Event{:host client, :service web_hit_404, :state nil, :description nil, :metric 62.0, :tags nil, :time 1421799106, :ttl nil}
```

**Comment by maguec** [comment]
The issue is that there is no TTL in the stream handling the fixed time window.
Adding a default ttl of fixed-time-window length + 1 fixed this
