### ISSUE TITLE
unclean close of SSE transport connection causes high cpu, memory leak

### ISSUE THREAD

**Issue by blalor** [aphyr/riemann#522]
I was playing around with curl and the sse transport to look at events as they're streaming in.  I've done this a few times, but somehow I triggered something that caused riemann to throw tons of exceptions and chew up a lot of memory.  I ended up restarting riemann because it was dropping events and becoming unusable. Judging by the stack trace, I think the closed connection wasn't detected by the transport.

```
ERROR [2015-03-04 15:04:21,995] New I/O worker #10 - lamina.core.utils - Unhandled exception in pipeline at riemann.transport.sse, line 48
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:487)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromSelectorLoop(AbstractNioWorker.java:158)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:114)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at aleph.netty.core$cached_thread_executor$reify__13593$fn__13594.invoke(core.clj:78)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

I was using this bash pipeline to sniff events:

    curl -s '172.17.0.19/sse/index?query=true' | egrep '^data: ' | cut -b 7- | jq -C 'select(.tags | contains(["consul"]))'

![screen shot 2015-03-04 at 10 14 25 am](https://cloud.githubusercontent.com/assets/109915/6486231/631e73b0-c257-11e4-890c-914f6cf6600c.png)

**Comment by aphyr** [comment]
Lamina hasn't been a part of the Riemann server for a couple releases now. Can you reproduce this behavior against a newer version?

**Comment by blalor** [comment]
This was something I saw only once, but the consequences were pretty severe.  Can be closed since the component’s no longer in play.

**Comment by aphyr** [comment]
Righto, thanks Brian. :)
