### ISSUE TITLE
Environment Variable

### ISSUE THREAD

**Issue by lowl4tency** [aphyr/riemann#610]
Hi, are there a way to pass an environment variable to riemann.config? I tried System/getenv but it doesn't work.

**Comment by bfritz** [comment]
Seems like `System/getenv` should work:

    $ lein uberjar

    $ cat <<EOF > test.config
    (prn (System/getenv "HOME"))
    EOF

    $ java -jar target/riemann-0.2.11-SNAPSHOT-standalone.jar test.config

    INFO [2015-09-24 10:01:24,776] main - riemann.bin - PID 23432
    "/home/brad"
    INFO [2015-09-24 10:01:24,789] main - riemann.core - Hyperspace core online

A copy of your config and some info about how you're launching riemann might help identify the issue.

**Comment by lowl4tency** [comment]
```$ echo $DATADOG_API_KEY
09XXXXXXXXXXXXXXXXXXXb4NNNNNNNf59
```
```user@server:~/riemann/riemann-0.2.10$ cat etc/riemann.config
; -*- mode: clojure; -*-
; vim: filetype=clojure

(logging/init {:file "riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "127.0.0.1"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 5)

; Datadog integration
(def DATADOG_API_KEY (System/getenv "DATADOG_API_KEY"))
(def ddog (datadog {:api-key DATADOG_API_KEY}))

(let [index (index)]
  ; Inbound events will be passed to these streams:
  (streams
    (default :ttl 60
      ; Index all events immediately.
       index

      ; Log expired events.
      (expired
        (fn [event] (info "expired" event))))
;     ddog
    (where (service #"chat.*") ddog)
    (where (service #"riemann.*") ddog)
    #(info %)))
```
```
INFO [2015-09-24 10:07:55,347] Thread-7 - riemann.config - #riemann.codec.Event{:host highstorm.cognician.com, :service riemann server ws 127.0.0.1:5556 in latency 0.99, :state ok, :description nil, :metric nil, :tags nil, :time 721551836517/500, :ttl 20}
WARN [2015-09-24 10:07:55,387] Thread-7 - riemann.config - riemann.datadog$datadog$fn__11380@333ea547 threw
clojure.lang.ExceptionInfo: clj-http: status 400 {:orig-content-encoding nil, :trace-redirects ["https://app.datadoghq.com/api/v1/series?api_key="], :request-time 38, :status 400, :headers {"Connection" "Close", "Content-Length" "0", "X-Content-Type-Options" "nosniff", "Strict-Transport-Security" "max-age=15724800;", "DD-POOL" "dogdispatcher", "Date" "Thu, 24 Sep 2015 14:07:55 GMT", "Content-Type" "text/plain; charset=UTF-8"}, :body ""}
        at clj_http.client$wrap_exceptions$fn__9677.invoke(client.clj:183)
        at clj_http.client$wrap_accept$fn__9829.invoke(client.clj:536)
        at clj_http.client$wrap_accept_encoding$fn__9835.invoke(client.clj:550)
        at clj_http.client$wrap_content_type$fn__9824.invoke(client.clj:525)
        at clj_http.client$wrap_form_params$fn__9906.invoke(client.clj:697)
        at clj_http.client$wrap_nested_params$fn__9923.invoke(client.clj:726)
        at clj_http.client$wrap_method$fn__9876.invoke(client.clj:641)
        at clj_http.cookies$wrap_cookies$fn__8113.invoke(cookies.clj:124)
        at clj_http.links$wrap_links$fn__8969.invoke(links.clj:51)
        at clj_http.client$wrap_unknown_host$fn__9932.invoke(client.clj:742)
        at clj_http.client$post.doInvoke(client.clj:857)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at riemann.datadog$post_datapoint.invoke(datadog.clj:27)
        at riemann.datadog$datadog$fn__11380.invoke(datadog.clj:47)
        at riemann.config$eval34$stream__81$fn__86.invoke(riemann.config:32)
        at riemann.config$eval34$stream__81.invoke(riemann.config:32)
        at riemann.core$stream_BANG_$fn__5727.invoke(core.clj:19)
        at riemann.core$stream_BANG_.invoke(core.clj:18)
        at riemann.core$instrumentation_service$measure__5736.invoke(core.clj:57)
        at riemann.service.ThreadService$thread_service_runner__3283$fn__3284.invoke(service.clj:71)
        at riemann.service.ThreadService$thread_service_runner__3283.invoke(service.clj:70)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by lowl4tency** [comment]
forgot export before variable. Solved
